name: TekZones
favicon: null
layout_spectrum: 0.5121976025402546
typography_spectrum: 0.46407205308787525
title: TekZones Specialties
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.012644050642848015
  lightness: 0.9955595878418535
  saturation: 0.5869457919616252
  rhythmicContrast: 0.5158952644560486
purpose: []
